[[main]]
name = "Home"
pageRef = "/"
weight = 1


[[main]]
name = "Posts"
pageRef = "posts"
weight = 3

[[main]]
name = "Resume"
pageRef = "resume"
weight = 4

[[main]]
name = "About"
pageRef = "about"
weight = 2

[[footer]]
name = "Site Information"
pageRef = "siteinfo"
weight = 2
